Repository jammsen/docker-palworld-dedicated-server, pull requests merged in 2024-01, with the labels that each got.

#34 Update README.md
  README.md
Labels: documentation, refactoring

#43 Preflight checking RPC & server credentials at runtime
  servermanager.sh
Labels: enhancement, good first issue, security

#94 [RFC] Adding portainer to README.MD and homogenizing text
  README.md
Labels: in-review

#129 removing portainer section, adding FAQ for Portainer
  README.md
Labels: documentation, enhancement

#135 Develop
  README.md
Labels: documentation, enhancement

#133 add FAQ: I have changed the `BaseCampWorkerMaxNum` settings, why are changes un-affected on the server?
  README.md
Labels: in-review
