Repository jammsen/docker-palworld-dedicated-server, pull requests merged in 2024-04, with the labels that each got.

#259 Exclude save backup directory in backup
  scripts/backupmanager.sh
Labels: in-review

#246 feat(error): throw when not running as root
  entrypoint.sh
Labels: good first issue, waiting-for-feedback

#241 Minimise user write access to container service files
  Dockerfile
  entrypoint.sh
  includes/config.sh
Labels: enhancement, security

#261 feat: log rotation
  docker-compose.yml
Labels: enhancement, help wanted, good first issue, refactoring
